Revert "feat: add `pwa.cache.*` option to precisely control caching (#1501)"
This reverts commit 1127c43823aac4db7fd80d5bb706ae7b1e129dc6.

diff --git a/tools/release b/tools/release
--- a/tools/release
+++ b/tools/release
@@ -27,7 +27,6 @@ NODE_CONFIG="package.json"
 CHANGE_LOG="docs/CHANGELOG.md"
 
 JS_DIST="assets/js/dist"
-PWA_SW="sw.min.js"
 BACKUP_PATH="$(mktemp -d)"
 
 FILES=(
@@ -71,14 +70,12 @@ _check_git() {
     exit 1
   fi
 
-  $opt_pre || (
-    if [[ $working_branch != "$DEFAULT_BRANCH" &&
-      $working_branch != hotfix/* &&
-      $working_branch != "$PROD_BRANCH" ]]; then
-      echo "> Abort: Please run on the default, release or patch branch."
-      exit 1
-    fi
-  )
+  if [[ $working_branch != "$DEFAULT_BRANCH" &&
+    $working_branch != hotfix/* &&
+    $working_branch != "$PROD_BRANCH" ]]; then
+    echo "> Abort: Please run on the default, release or patch branch."
+    exit 1
+  fi
 }
 
 _check_src() {
@@ -159,7 +156,7 @@ build_gem() {
   rm -f ./*.gem
 
   npm run build
-  git add "$JS_DIST" "$PWA_SW" -f # add JS distribution files to gem
+  git add "$JS_DIST" -f # add JS dist to gem
   gem build "$GEM_SPEC"
   cp "$JS_DIST"/* "$BACKUP_PATH"
 
